# Source: calico/templates/calico-kube-controllers.yaml
# This manifest creates a Pod Disruption Budget for Controller to allow K8s Cluster Autoscaler to evict

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "calicoCni.name" . }}-kube-controllers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calicoCni.calicoKubeControllers.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.calicoKubeControllers.minAvailable }}
  selector:
    matchLabels:
      {{- include "calicoCni.calicoKubeControllers.matchLabels" . | nindent 6 }}
