{{- if and (.Values.secret.create) (.Values.secret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "vngcloud-controller-manager-config" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ if .Values.cloudConfigContents -}}
  vcontainer-ccm.conf: |
    {{ .Values.cloudConfigContents | b64enc }}
  {{ else -}}
  vcontainer-ccm.conf: {{ include "cloudConfig" . | b64enc }}
  {{ end -}}
{{- end }}
