{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "vconCcm.labels" . | nindent 4 }}
  name: {{ include "vconCcm.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 10258
    protocol: TCP
  selector:
    {{- include "vconCcm.controllermanager.matchLabels" . | nindent 4 }}
{{- end }}
