{{- if .Values.csi.plugin.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "vcontainer-storage-interface.controllerplugin.labels" . | nindent 4 }}
  name: {{ include "vcontainer-storage-interface.name" . }}-controllerplugin
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: component
  selector:
    matchLabels:
      {{- include "vcontainer-storage-interface.controllerplugin.matchLabels" . | nindent 6 }}
{{- end }}