{{ if .Values.vcontainerConfig.create }}
apiVersion: v1
kind: Secret
metadata:
  name: vcontainer-csi-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  vcontainer-csi-config.conf: |-
    [Global]
    identity-url={{ printf "%s" .Values.vcontainerConfig.identityURL }}
    vserver-url={{ printf "%s" .Values.vcontainerConfig.vserverURL }}
    client-id={{ printf "%s" .Values.vcontainerConfig.clientID }}
    client-secret={{ printf "%s" .Values.vcontainerConfig.clientSecret }}
{{ end }}