apiVersion: v2
appVersion: v0.0.0
version: 0.0.3
name: vngcloud-capi-controller-manager
description: VngCloud Controller Manager plugin for Kubernetes
type: application
maintainers:
  - name: Cuong. Duong Manh
    email: cuongdm3@vng.com.vn
