apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:  
  name: {{ include "vngcloud-capi-metrics-controller.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "vngcloud-capi-metrics-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vngcloud-capi-metrics-controller.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "vngcloud-capi-metrics-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}